name: macOS build

on:
  workflow_run:
    workflows: ["Code Quality"]
    types: [completed]
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Check out repo
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable

    - name: Build CLI
      run: cargo build --release -p cards-cli

    - name: Build GUI
      run: cargo build --release -p cards-gui

    - name: Upload CLI artifact
      uses: actions/upload-artifact@v4
      with:
        name: cards-cli-macOS
        path: target/release/cards

    - name: Upload GUI artifact
      uses: actions/upload-artifact@v4
      with:
        name: cards-gui-macOS
        path: target/release/cards-gui
