name: macOS build

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Install dependencies
      run: poetry install --no-interaction --no-root
    - name: Package Application
      run: |
        source .venv/bin/activate
        pyinstaller --onefile cards/cards.py
    - uses: actions/upload-artifact@v2
      with:
        name: cards-macOS
        path: dist/cards