name: Package Application with Pyinstaller

on: [push, pull_request]

steps:
- uses: actions/checkout@v2
- uses: actions/setup-python@v2
  with:
    python-version: '3.9'
- uses: snok/install-poetry@v1
- run: scripts/distribute.sh

