name: Package Application with Pyinstaller

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: cards

    - uses: actions/upload-artifact@v2
      with:
        name: cards
        path: cards/dist/windows

